# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gaia_object.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import google.protobuf.descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gaia_object.proto',
  package='gaia.object',
  serialized_pb='\n\x11gaia_object.proto\x12\x0bgaia.object\x1a google/protobuf/descriptor.proto\"\x90\x01\n\x0ePackagedObject\x12\x12\n\x07version\x18\x01 \x02(\x03:\x01\x31\x12\x0e\n\x06prefix\x18\x02 \x02(\x0c\x12\x0b\n\x03key\x18\x03 \x02(\x0c\x12\x10\n\x08\x63\x61ss_key\x18\x04 \x02(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x05 \x02(\x0c\x12\x15\n\rlast_modified\x18\x06 \x01(\x03\x12\x16\n\x07\x64\x65leted\x18\x07 \x01(\x08:\x05\x66\x61lse:6\n\x0bgaia_object\x12\x1f.google.protobuf.MessageOptions\x18\xd0\x86\x03 \x01(\x08:,\n\x03key\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\x08:,\n\x03ref\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x08:,\n\x03set\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x08\x42#\n\x15\x63om.cootek.data.protoB\nGaiaObject')


GAIA_OBJECT_FIELD_NUMBER = 50000
gaia_object = _descriptor.FieldDescriptor(
  name='gaia_object', full_name='gaia.object.gaia_object', index=0,
  number=50000, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
KEY_FIELD_NUMBER = 50000
key = _descriptor.FieldDescriptor(
  name='key', full_name='gaia.object.key', index=1,
  number=50000, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
REF_FIELD_NUMBER = 50001
ref = _descriptor.FieldDescriptor(
  name='ref', full_name='gaia.object.ref', index=2,
  number=50001, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
SET_FIELD_NUMBER = 50002
set = _descriptor.FieldDescriptor(
  name='set', full_name='gaia.object.set', index=3,
  number=50002, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_PACKAGEDOBJECT = _descriptor.Descriptor(
  name='PackagedObject',
  full_name='gaia.object.PackagedObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='gaia.object.PackagedObject.version', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='gaia.object.PackagedObject.prefix', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='gaia.object.PackagedObject.key', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cass_key', full_name='gaia.object.PackagedObject.cass_key', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='gaia.object.PackagedObject.data', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_modified', full_name='gaia.object.PackagedObject.last_modified', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deleted', full_name='gaia.object.PackagedObject.deleted', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=69,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['PackagedObject'] = _PACKAGEDOBJECT

class PackagedObject(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKAGEDOBJECT

  # @@protoc_insertion_point(class_scope:gaia.object.PackagedObject)

google.protobuf.descriptor_pb2.MessageOptions.RegisterExtension(gaia_object)
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(key)
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(ref)
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(set)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\025com.cootek.data.protoB\nGaiaObject')
# @@protoc_insertion_point(module_scope)
