FROM mysql:5.7.26
#设置免密登录
ENV MYSQL_ALLOW_EMPTY_PASSWORD yes
#将所需文件放到容器中
RUN mkdir /mysql
WORKDIR /mysql
COPY contrib/docker/mysql/setup.sh .
#COPY schema.sql /mysql/schema.sql
COPY contrib/docker/mysql/privileges.sql .
#设置容器启动时执行的命令
CMD ["sh", "/mysql/setup.sh"]
